T-5698[ADD]base_confirmation_requirement_rules: base module for confirmation requirements
sygel-technology/sy-server-tools pull request #4
Opened 2024-03-25 15:54 UTC by manuelregidor

2024-03-25 16:55 UTC, ValentinVinagre requested changes
algunos cambios

2024-03-25 16:55 UTC, ValentinVinagre commented on base_confirmation_requirement_rules/models/requirement_rule_type_mixin.py
> +    _description = "Requirement Rule Type"
falta un mixin en la descripcion

2024-03-25 16:55 UTC, ValentinVinagre commented on base_confirmation_requirement_rules/models/confirmation_requirement_mixin.py
> +            lambda a: a[self._type_field["type"]] and
no sería mejor un .get(campo, False)?

2024-03-25 16:55 UTC, ValentinVinagre commented on base_confirmation_requirement_rules/models/confirmation_requirement_mixin.py
> +                if self.search_count(domain) != 1:
porque distinto? no tendría que ser >1?

2024-03-25 16:55 UTC, ValentinVinagre commented on base_confirmation_requirement_rules/models/confirmation_requirement_rule_mixin.py
> +    error_description = fields.Text(
no lo hacemos traducible?

2024-03-25 16:57 UTC, ValentinVinagre commented
Se tendría que crear un grupo de permisos especial/general desde el cual no se tengan en cuenta nunca las validaciones.

2024-03-26 06:20 UTC, manuelregidor commented on base_confirmation_requirement_rules/models/confirmation_requirement_mixin.py
> +                if self.search_count(domain) != 1:
Es != 1 porque el único valor válido para que no salte el error es 1, ni mayor ni menor.

2024-03-26 06:33 UTC, manuelregidor commented on base_confirmation_requirement_rules/models/confirmation_requirement_mixin.py
> +            lambda a: a[self._type_field["type"]] and
¿Te refieres a poner a[self._type_field.get("type", False)] o a otra cosa?

2024-03-26 06:42 UTC, manuelregidor commented
> Se tendría que crear un grupo de permisos especial/general desde el cual no se tengan en cuenta nunca las validaciones.

¿Hago también un grupo específico para ventas y albaranes en su módulo correspondiente para saltar las restricciones solamente en esos modelos?

2024-03-26 08:03 UTC, ValentinVinagre commented on base_confirmation_requirement_rules/models/confirmation_requirement_mixin.py
> +                if self.search_count(domain) != 1:
pero si no encuentra ninguno tendría que dar error?

2024-03-26 08:04 UTC, ValentinVinagre commented on base_confirmation_requirement_rules/models/confirmation_requirement_mixin.py
> +            lambda a: a[self._type_field["type"]] and
exactamente

2024-03-26 08:04 UTC, ValentinVinagre commented
> > Se tendría que crear un grupo de permisos especial/general desde el cual no se tengan en cuenta nunca las validaciones.
> 
> ¿Hago también un grupo específico para ventas y albaranes en su módulo correspondiente para saltar las restricciones solamente en esos modelos?

uno general ya está bien.

2024-03-26 08:05 UTC, manuelregidor commented on base_confirmation_requirement_rules/models/confirmation_requirement_mixin.py
> +            lambda a: a[self._type_field["type"]] and
Como prefieras, pero en caso de existir va a dar un error lo hagamos de un modo u otro.

2024-03-26 08:07 UTC, manuelregidor commented on base_confirmation_requirement_rules/models/confirmation_requirement_mixin.py
> +                if self.search_count(domain) != 1:
Precisamente si da 0 es porque no se han cumplido las condiciones.

2024-03-26 08:12 UTC, ValentinVinagre commented on base_confirmation_requirement_rules/models/confirmation_requirement_mixin.py
> +                if self.search_count(domain) != 1:
humm me preocupa tema de cache, pero déjalo así entonces

2024-03-26 08:13 UTC, ValentinVinagre commented on base_confirmation_requirement_rules/models/confirmation_requirement_mixin.py
> +            lambda a: a[self._type_field["type"]] and
pero en caso de no estar la key no dará un petazo de todo el trazeback, se podrá controlar.

2024-03-26 13:51 UTC, manuelregidor commented
@ValentinVinagre Hecho

2024-03-26 14:55 UTC, ValentinVinagre requested changes
@manuelregidor algunos cambios mas

2024-03-26 14:55 UTC, ValentinVinagre commented on base_confirmation_requirement_rules/data/confirmation_requirement_data.xml
> +    <record id="group_skip_confirmation_requirement_rules" model="res.groups">
tiene que estar el admin por defecto. Por otro lado falta el noupdate ya que si no, siempre se perderá la configuración.

2024-03-26 14:55 UTC, ValentinVinagre commented on base_confirmation_requirement_rules/models/confirmation_requirement_mixin.py
> +                a[self._type_field.get("type", False)].use_requirement_rules and
aquí el get no es necesario ya que si en el primero da FALSE ya no se sigue comprobando debido a los ands. cambialo please

2024-03-26 15:39 UTC, manuelregidor commented
@ValentinVinagre Ya está

2024-03-26 16:51 UTC, merged